#!/bin/bash
params=( $(getopt --unquoted --longoptions vip:,target:,password:,global-masquerade,vip-id: --options "" -- ${@} ) ) ;
i=0 ;
while [[ ${params[i]} != -- ]]; do
	case "${params[i]}" in
		--vip)
			i=$[ ${i} + 1 ] ;
			VIP=${params[i]} ;;
		--target)
			i=$[ ${i} + 1 ] ;
			TARGET=${params[i]} ;;
		--password)
			i=$[ ${i} + 1 ] ;
			PASSWORD=${params[i]} ;;
		--global-masquerade)
			GLOBAL_MASQUERADE=true ;;
		--vip-id)
			i=$[ ${i} + 1 ] ;
			VIP_ID=${params[i]} ;;
		*)
			echo "unrecognized param: ${params[i]}" >&2;
			exit 1;;
	esac &&
	i=$(( ${i} + 1 ));
done ;
for param in VIP TARGET PASSWORD; do
	if [[ -z ${!param} ]]; then
		echo "invalid or missing ${param} param" >&2;
		exit 1;
	fi;
done;
if [[ "${GLOBAL_MASQUERADE}" != 'true' ]]; then
	GLOBAL_MASQUERADE=false;
fi;

iface=$(ip route show default  |cut -d ' ' -f 5) &&
addrInfo=( $(ip addr show ${iface} |grep inet |grep -v inet6 |grep -v secondary) ) &&
IFS=/ addrMask=( ${addrInfo[1]} ) &&
addr=${addrMask[0]}  &&
mask=${addrMask[1]}  &&
if [[ -z "${VIP_ID}" ]]; then
	VIP_ID=$(echo ${VIP} |cut -d . -f 4) ;
fi &&
prio=$(( ${RANDOM} % 255 + 1 )) &&

echo "starting ucarp: " &&
echo "VIP: ${VIP}" &&
echo "TARGET: ${TARGET}" &&
echo "iface: ${iface} ${addr}/${mask}" &&
echo "VIP_ID: ${VIP_ID}" &&
echo "prio: ${prio}" &&
echo "GLOBAL_MASQUERADE: ${GLOBAL_MASQUERADE}" &&

exec ucarp -z -n -u ./vip-add -d ./vip-del -p ${PASSWORD} -k ${prio} \
	-i ${iface} -s ${addr} -a ${VIP} -v ${VIP_ID} -x "${mask} ${TARGET} ${GLOBAL_MASQUERADE}"
