#!/bin/bash
iface=${1} ;
vip=${2} ;
extraParams=( ${3} ) ; # for example "24 10.33.0.4 false"
mask=${extraParams[0]} ;
target=${extraParams[1]} ;
globalMasquerade=${extraParams[2]} ;
iptablesCmd='-A' ;
ipCmd=add ;
if [[ ${0} == *vip-del ]]; then
	ipCmd=del ;
	iptablesCmd='-D' ;
fi ;

ip addr ${ipCmd} ${vip}/${mask} dev ${iface} &&
iptables -t nat ${iptablesCmd} PREROUTING -d ${vip} -j DNAT --to-destination ${target} &&
if ${globalMasquerade}; then
	iptables -t nat ${iptablesCmd} POSTROUTING -j MASQUERADE ;
else
	iptables -t nat ${iptablesCmd} POSTROUTING -d ${target} -j SNAT --to-source ${vip} ;
fi ;
